drop view if exists item_company;
drop view if exists item_fullinfo;

drop table if exists item_container;
drop table if exists item_ship;
drop table if exists item_state;
drop table if exists staff_city;
drop table if exists staff_company;
drop table if exists tax_info;
drop table if exists staff_handle_item;
drop table if exists item_route;
drop table if exists verification;
drop table if exists staff;
drop table if exists city;
drop table if exists ship;
drop table if exists company;
drop table if exists item;
drop table if exists container;
drop table if exists item_type;